-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.cart
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    adult_quantity integer,
    child_quantity integer,
    created_at timestamp(6) without time zone,
    infant_quantity integer,
    tour_schedule_id integer NOT NULL,
    updated_at timestamp(6) without time zone,
    tour_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT cart_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.categories
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    category_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    display_order integer,
    image_url character varying(500) COLLATE pg_catalog."default",
    slug character varying(255) COLLATE pg_catalog."default" NOT NULL,
    status character varying(255) COLLATE pg_catalog."default",
    parent_id bigint,
    CONSTRAINT categories_pkey PRIMARY KEY (id),
    CONSTRAINT ukoul14ho7bctbefv8jywp5v3i2 UNIQUE (slug)
);

CREATE TABLE IF NOT EXISTS public.contacts
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    admin_reply text COLLATE pg_catalog."default",
    created_at timestamp(6) without time zone,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    full_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    message text COLLATE pg_catalog."default" NOT NULL,
    phone character varying(20) COLLATE pg_catalog."default",
    replied_at timestamp(6) without time zone,
    CONSTRAINT contacts_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.coupon_usage
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    discount_amount numeric(15, 2) NOT NULL,
    order_id integer NOT NULL,
    used_at timestamp(6) without time zone,
    coupon_id bigint NOT NULL,
    user_id bigint,
    CONSTRAINT coupon_usage_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.coupons
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    coupon_code character varying(50) COLLATE pg_catalog."default" NOT NULL,
    coupon_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    max_usage_total integer,
    status character varying(255) COLLATE pg_catalog."default",
    valid_from timestamp(6) without time zone NOT NULL,
    valid_to timestamp(6) without time zone NOT NULL,
    created_by bigint,
    CONSTRAINT coupons_pkey PRIMARY KEY (id),
    CONSTRAINT ukf1u99ssbdsqass9ntq968codg UNIQUE (coupon_code)
);

CREATE TABLE IF NOT EXISTS public.notifications
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    content text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp(6) without time zone,
    is_read boolean,
    notification_type character varying(50) COLLATE pg_catalog."default",
    reference_id integer,
    title character varying(500) COLLATE pg_catalog."default" NOT NULL,
    user_id bigint,
    CONSTRAINT notifications_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.order_details
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    adult_price numeric(15, 2),
    adult_quantity integer,
    child_price numeric(15, 2),
    child_quantity integer,
    departure_date date NOT NULL,
    infant_price numeric(15, 2),
    infant_quantity integer,
    return_date date NOT NULL,
    subtotal numeric(15, 2) NOT NULL,
    tour_name character varying(500) COLLATE pg_catalog."default" NOT NULL,
    order_id bigint NOT NULL,
    tour_id bigint NOT NULL,
    tour_schedule_id bigint NOT NULL,
    CONSTRAINT order_details_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.order_participants
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    date_of_birth date,
    full_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    gender character varying(255) COLLATE pg_catalog."default",
    nationality character varying(100) COLLATE pg_catalog."default",
    participant_type character varying(255) COLLATE pg_catalog."default" NOT NULL,
    passport_number character varying(50) COLLATE pg_catalog."default",
    special_requirements text COLLATE pg_catalog."default",
    order_detail_id integer NOT NULL,
    CONSTRAINT order_participants_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.orders
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    admin_note text COLLATE pg_catalog."default",
    customer_note text COLLATE pg_catalog."default",
    discount_amount numeric(15, 2),
    final_amount numeric(15, 2) NOT NULL,
    order_code character varying(50) COLLATE pg_catalog."default" NOT NULL,
    order_status character varying(255) COLLATE pg_catalog."default",
    payment_date timestamp(6) without time zone,
    payment_method character varying(50) COLLATE pg_catalog."default",
    payment_status character varying(255) COLLATE pg_catalog."default",
    total_amount numeric(15, 2) NOT NULL,
    transaction_id character varying(255) COLLATE pg_catalog."default",
    user_id bigint,
    CONSTRAINT orders_pkey PRIMARY KEY (id),
    CONSTRAINT ukdhk2umg8ijjkg4njg6891trit UNIQUE (order_code)
);

CREATE TABLE IF NOT EXISTS public.reviews
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    admin_reply text COLLATE pg_catalog."default",
    comment text COLLATE pg_catalog."default",
    created_at timestamp(6) without time zone,
    images text COLLATE pg_catalog."default",
    is_verified_purchase boolean,
    location_rating integer,
    price_rating integer,
    rating integer NOT NULL,
    replied_at timestamp(6) without time zone,
    service_rating integer,
    status character varying(255) COLLATE pg_catalog."default",
    title character varying(500) COLLATE pg_catalog."default",
    updated_at timestamp(6) without time zone,
    order_id bigint,
    tour_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT reviews_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.roles
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    description text COLLATE pg_catalog."default",
    role_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT roles_pkey PRIMARY KEY (id),
    CONSTRAINT uk716hgxp60ym1lifrdgp67xt5k UNIQUE (role_name)
);

CREATE TABLE IF NOT EXISTS public.settings
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    description text COLLATE pg_catalog."default",
    group_name character varying(100) COLLATE pg_catalog."default",
    setting_key character varying(100) COLLATE pg_catalog."default" NOT NULL,
    setting_type character varying(50) COLLATE pg_catalog."default",
    setting_value text COLLATE pg_catalog."default",
    updated_at timestamp(6) without time zone,
    CONSTRAINT settings_pkey PRIMARY KEY (id),
    CONSTRAINT ukswd05dvj4ukvw5q135bpbbfae UNIQUE (setting_key)
);

CREATE TABLE IF NOT EXISTS public.statistics_daily
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    created_at timestamp(6) without time zone,
    new_users integer,
    page_views integer,
    stat_date date NOT NULL,
    total_bookings integer,
    total_orders integer,
    total_revenue numeric(15, 2),
    CONSTRAINT statistics_daily_pkey PRIMARY KEY (id),
    CONSTRAINT ukie1uegiexuw7mpemg7f1apdof UNIQUE (stat_date)
);

CREATE TABLE IF NOT EXISTS public.tour_detail
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    day_number character varying(255) COLLATE pg_catalog."default" NOT NULL,
    day_title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    dep character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    image character varying(500) COLLATE pg_catalog."default",
    tour_id bigint,
    CONSTRAINT tour_detail_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tour_schedules
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    available_seats integer NOT NULL,
    booked_seats integer,
    departure_date date NOT NULL,
    note text COLLATE pg_catalog."default",
    return_date date NOT NULL,
    status character varying(255) COLLATE pg_catalog."default",
    tour_id bigint NOT NULL,
    CONSTRAINT tour_schedules_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tours
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    adult_price numeric(15, 2) NOT NULL,
    base_price numeric(15, 2) NOT NULL,
    child_price numeric(15, 2),
    departure_location character varying(255) COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    destination character varying(255) COLLATE pg_catalog."default",
    duration_days integer NOT NULL,
    duration_nights integer NOT NULL,
    featured_image character varying(500) COLLATE pg_catalog."default",
    infant_price numeric(15, 2),
    rating_average numeric(3, 2),
    short_description text COLLATE pg_catalog."default",
    slug character varying(500) COLLATE pg_catalog."default" NOT NULL,
    status character varying(255) COLLATE pg_catalog."default",
    total_reviews integer,
    tour_code character varying(50) COLLATE pg_catalog."default" NOT NULL,
    tour_name character varying(500) COLLATE pg_catalog."default" NOT NULL,
    video_url character varying(500) COLLATE pg_catalog."default",
    view_count integer,
    category_id bigint,
    created_by bigint,
    CONSTRAINT tours_pkey PRIMARY KEY (id),
    CONSTRAINT uko61q2fu99qfi7hvheq6lnntim UNIQUE (slug),
    CONSTRAINT ukr20eechhviuokimbwk1qqs7vn UNIQUE (tour_code)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    address text COLLATE pg_catalog."default",
    avatar_url character varying(500) COLLATE pg_catalog."default",
    date_of_birth date,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email_verified boolean,
    full_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    gender character varying(255) COLLATE pg_catalog."default",
    password_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(20) COLLATE pg_catalog."default",
    status character varying(255) COLLATE pg_catalog."default",
    role_id bigint NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.wishlists
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    created_at timestamp(6) without time zone,
    tour_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT wishlists_pkey PRIMARY KEY (id),
    CONSTRAINT uk3xnqtpnv14pq6wppon2be4ryx UNIQUE (user_id, tour_id)
);

ALTER TABLE IF EXISTS public.cart
    ADD CONSTRAINT fk8sa76crlbhwjnctf7u1j6pl0r FOREIGN KEY (tour_id)
    REFERENCES public.tours (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.cart
    ADD CONSTRAINT fkg5uhi8vpsuy0lgloxk2h4w5o6 FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.categories
    ADD CONSTRAINT fksaok720gsu4u2wrgbk10b5n8d FOREIGN KEY (parent_id)
    REFERENCES public.categories (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coupon_usage
    ADD CONSTRAINT fkcsx5pbxjnp6jvuveb3lxyklhe FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coupon_usage
    ADD CONSTRAINT fkof9h3rw1vu403j5dbehr45ts2 FOREIGN KEY (coupon_id)
    REFERENCES public.coupons (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coupons
    ADD CONSTRAINT fk5ta2iuowjf2sx01vtu35oi2an FOREIGN KEY (created_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.notifications
    ADD CONSTRAINT fk9y21adhxn0ayjhfocscqox7bh FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.order_details
    ADD CONSTRAINT fkd538hy0bddc3rdtt5j7xhq5wg FOREIGN KEY (tour_schedule_id)
    REFERENCES public.tour_schedules (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.order_details
    ADD CONSTRAINT fkjyu2qbqt8gnvno9oe9j2s2ldk FOREIGN KEY (order_id)
    REFERENCES public.orders (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.order_details
    ADD CONSTRAINT fkocnhsogm8afeio2qvt85ppw91 FOREIGN KEY (tour_id)
    REFERENCES public.tours (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.order_participants
    ADD CONSTRAINT fkdqs9u7lrjaaian4nlcxir065b FOREIGN KEY (order_detail_id)
    REFERENCES public.order_details (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT fk32ql8ubntj5uh44ph9659tiih FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.reviews
    ADD CONSTRAINT fkcgy7qjc1r99dp117y9en6lxye FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.reviews
    ADD CONSTRAINT fkg95fdc12cdl5o06q6la9jh0dm FOREIGN KEY (tour_id)
    REFERENCES public.tours (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.reviews
    ADD CONSTRAINT fkqwgq1lxgahsxdspnwqfac6sv6 FOREIGN KEY (order_id)
    REFERENCES public.orders (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tour_detail
    ADD CONSTRAINT fkbbx7pnbbsqo4fja8d4rfe6nw1 FOREIGN KEY (tour_id)
    REFERENCES public.tours (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tour_schedules
    ADD CONSTRAINT fka7bvkxeyqhbppi24qimguq9un FOREIGN KEY (tour_id)
    REFERENCES public.tours (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tours
    ADD CONSTRAINT fk4mwn5rnlqad3gi9lm0yddhoy4 FOREIGN KEY (category_id)
    REFERENCES public.categories (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tours
    ADD CONSTRAINT fkiacs56q9m5figgjdtq61w2qxr FOREIGN KEY (created_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT fkp56c1712k691lhsyewcssf40f FOREIGN KEY (role_id)
    REFERENCES public.roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.wishlists
    ADD CONSTRAINT fk15x4y35ce2aj27lb8vlr253qy FOREIGN KEY (tour_id)
    REFERENCES public.tours (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.wishlists
    ADD CONSTRAINT fk330pyw2el06fn5g28ypyljt16 FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;


